name: "Tests"

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Select 1"]
    types:
      - completed

jobs:
  ShowEnv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: environment
    - run: |
        cat environment.yaml

